version: '3'

services:

  pretix:
    image: 'pretix/standalone:stable'
    container_name: pretix_app
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - /mnt/docker/pretix/data:/data
      - /mnt/docker/pretix/conf:/etc/pretix
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=80"
    ports:
      - 80:80
    networks:
      - web
      - stack_network

  db:
    image: postgres:12.0-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix
    volumes:
      - /mnt/docker/pretix/postgresql:/var/lib/postgresql/data
    networks:
      - stack_network

  redis:
    image: redis:latest
    restart: always
    networks:
      - stack_network

networks:
  web:
    external: true
  stack_network:
    external: false

